import { useEffect } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';

export default function TermsOfService() {
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <div className="page-wrapper">
      <Helmet>
        <title>Terms of Service | Varsaka Labs</title>
        <meta 
          name="description" 
          content="Terms of Service governing the use of Varsaka Labs website, Quality Engineering services, and client engagements under Indian law." 
        />
      </Helmet>

      <div className="prose-block">
        <div className="section-tag">⚖️ Legal & Compliance</div>
        <h1>Terms of Service</h1>
        <p className="meta">
          Effective Date: September 2026 | Governed by the Information Technology Act, 2000 and Indian Contract Act, 1872
        </p>

        <section>
          <h2>1. Electronic Record & Legal Acceptance</h2>
          <p>
            This document is an electronic record generated by a computer system and does not require physical or digital signatures pursuant to the <strong>Information Technology Act, 2000</strong> and rules made thereunder.
          </p>
          <p>
            These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "Client", or "you") and <strong>Varsaka Labs</strong> ("Company", "we", "our", or "us"), governing your access to and use of our website (<a href="https://varsaka.com">varsaka.com</a>), applications, QA testing portals, and related professional services.
          </p>
          <p>
            By accessing, browsing, or utilizing this website or engaging our services, you confirm that you have read, understood, and agree to be bound by these Terms, together with our <Link to="/privacy-policy">Privacy Policy</Link>, <Link to="/cookies-policy">Cookies Policy</Link>, and <Link to="/refund-policy">Refund & Cancellation Policy</Link>.
          </p>
        </section>

        <section>
          <h2>2. Eligibility & Capacity to Contract</h2>
          <p>
            Under Section 11 of the <strong>Indian Contract Act, 1872</strong>, you represent and warrant that you are at least 18 years of age and possess full legal capacity to enter into binding legal agreements. If you are accessing this website on behalf of a corporation, partnership, or other legal entity, you represent and warrant that you have full corporate authority to bind that entity to these Terms.
          </p>
        </section>

        <section>
          <h2>3. Scope of Services & Statements of Work (SOW)</h2>
          <p>
            Varsaka Labs provides full-spectrum Software Quality Engineering (QE) and testing services, including but not limited to:
          </p>
          <ul>
            <li>Functional, Regression, and Exploratory Testing</li>
            <li>Automated End-to-End Test Framework Engineering (Playwright, Cypress, Selenium)</li>
            <li>API Contract, Performance, Stress, and Load Testing (k6, JMeter)</li>
            <li>Vulnerability Assessment & Web/Mobile Security Testing</li>
            <li>Quality Engineering Consulting, Staff Augmentation, and Cohort Training Programs</li>
          </ul>
          <p>
            Website content, rate cards, and marketing materials are for informational purposes and do not constitute a formal offer of contract. Specific commercial terms, deliverables, milestones, acceptance criteria, and service level agreements (SLAs) for any client engagement shall be defined in a mutually executed <strong>Statement of Work (SOW)</strong> or Master Services Agreement (MSA), which shall supersede these general terms in the event of any direct conflict.
          </p>
        </section>

        <section>
          <h2>4. Authorized Testing & Ethical Conduct</h2>
          <p>
            As a Quality Engineering organization, Varsaka Labs strictly adheres to ethical hacking and authorized security testing protocols:
          </p>
          <ul>
            <li><strong>Authorization Requirement:</strong> Clients must have full legal ownership or explicit, written authorization from system owners before engaging Varsaka Labs to conduct security testing, penetration testing, or stress tests on any digital asset, network, or server.</li>
            <li><strong>Prohibited Misuse:</strong> Users and visitors are strictly prohibited from using our website, APIs, or infrastructure to transmit viruses, malware, trojans, or illicit code, or to attempt unauthorized penetration, denial-of-service (DoS) attacks, or reverse engineering of our systems pursuant to Sections 43, 66, and 66A of the <strong>Information Technology Act, 2000</strong>.</li>
            <li><strong>Honeypot & Bot Defense:</strong> Our digital forms employ automated bot traps and rate limiting. Submitting automated spam or malicious payloads may result in immediate IP banning and reporting to cybersecurity authorities (CERT-In).</li>
          </ul>
        </section>

        <section>
          <h2>5. Intellectual Property Rights</h2>
          <p>
            <strong>Client Intellectual Property:</strong> Clients retain exclusive and complete ownership of all intellectual property rights in their proprietary source code, software, documentation, business logic, customer data, and test environments shared with Varsaka Labs.
          </p>
          <p>
            <strong>Deliverables:</strong> Upon full and final settlement of all applicable invoices under the relevant SOW, all test plans, test cases, and custom test scripts authored specifically for the client shall become the client's intellectual property.
          </p>
          <p>
            <strong>Company Intellectual Property:</strong> Varsaka Labs retains all rights, title, and interest in its pre-existing automation libraries, proprietary testing frameworks, methodology accelerators, website designs, trademarks, logos, and trade secrets.
          </p>
        </section>

        <section>
          <h2>6. Fees, Invoicing & Payment Terms</h2>
          <p>
            All fees for professional engagements are specified in the applicable SOW. Unless otherwise agreed in writing:
          </p>
          <ul>
            <li>Invoices are issued in Indian National Rupees (INR) for domestic clients and United States Dollars (USD) for international clients.</li>
            <li>All fees are subject to applicable Goods and Services Tax (GST) under Indian tax laws or international withholding taxes as required.</li>
            <li>Invoices are payable within the net credit period stated on the invoice (typically 15 to 30 calendar days). Late payments may attract interest at 1.5% per month or the maximum permissible under Indian law.</li>
          </ul>
        </section>

        <section>
          <h2>7. Disclaimer of Warranties & Quality Assurance Scope</h2>
          <p>
            Software quality engineering and defect detection substantially mitigate risk and improve software stability; however, given the infinite combinations of real-world computing environments, hardware variations, and third-party dependencies:
          </p>
          <p>
            <strong>No Guarantee of Error-Free Software:</strong> Varsaka Labs does not warrant or guarantee that any tested software will be completely bug-free, uninterrupted, or invulnerable to novel zero-day cyber threats. All services and website contents are delivered with reasonable professional skill and diligence on an <em>"as is"</em> and <em>"as available"</em> standard.
          </p>
        </section>

        <section>
          <h2>8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable Indian law:
          </p>
          <ul>
            <li>Neither party shall be liable to the other for any indirect, incidental, punitive, special, or consequential damages (including loss of profits, revenue, data, goodwill, or business interruption) arising out of or related to this website or our services.</li>
            <li>Varsaka Labs' total aggregate liability arising out of or in connection with any engagement, whether in contract, tort (including negligence), or otherwise, shall be strictly capped at the total amount actually paid by the client to Varsaka Labs under the specific Statement of Work giving rise to the claim during the preceding six (6) months.</li>
          </ul>
        </section>

        <section>
          <h2>9. Non-Solicitation</h2>
          <p>
            During the term of any active service engagement and for a period of twelve (12) months following its termination or expiration, neither party shall, directly or indirectly, solicit, hire, or entice away any engineer, consultant, or staff member of the other party who was actively involved in the delivery or receipt of services, without the prior written consent of the other party.
          </p>
        </section>

        <section>
          <h2>10. Dispute Resolution & Governing Law (Arbitration)</h2>
          <p>
            These Terms, along with any disputes, controversies, or claims arising out of or relating to them, shall be governed by and construed in accordance with the substantive laws of the <strong>Republic of India</strong>, without regard to conflict of laws principles.
          </p>
          <p>
            <strong>Amicable Resolution:</strong> In the event of any dispute, the parties shall first attempt to resolve the matter through mutual, good-faith executive consultations within thirty (30) days of written notice.
          </p>
          <p>
            <strong>Arbitration:</strong> Any dispute that cannot be resolved amicably shall be referred to and finally resolved by binding arbitration in accordance with the <strong>Arbitration and Conciliation Act, 1996</strong> (as amended). The arbitration shall be conducted by a sole arbitrator mutually appointed by the parties.
          </p>
          <ul>
            <li><strong>Seat & Venue of Arbitration:</strong> Hyderabad, Telangana, India.</li>
            <li><strong>Language of Proceedings:</strong> English.</li>
            <li><strong>Jurisdiction:</strong> Subject to arbitration, the courts situated in <strong>Hyderabad, Telangana, India</strong> shall possess sole and exclusive jurisdiction.</li>
          </ul>
        </section>

        <section>
          <h2>11. Contact & Legal Notices</h2>
          <p>
            For any legal queries, notices, or formal correspondence regarding these Terms of Service, please contact:
          </p>
          <div style={{ background: 'var(--bg-light, #f8fafc)', border: '1px solid var(--border, #e2e8f0)', borderRadius: '12px', padding: '20px 24px', margin: '20px 0' }}>
            <p style={{ margin: '0 0 6px', fontWeight: 700, color: 'var(--text)' }}>Legal Department - Varsaka Labs</p>
            <p style={{ margin: '0 0 6px' }}><strong>Email:</strong> <a href="mailto:info@varsaka.com">info@varsaka.com</a></p>
            <p style={{ margin: '0 0 6px' }}><strong>Registered Operations:</strong> Gachibowli, Hyderabad, Telangana 500032, India</p>
            <p style={{ margin: 0 }}><strong>Phone / WhatsApp:</strong> +91 7396106271</p>
          </div>
        </section>
      </div>
    </div>
  );
}
